language: c

os:
- osx

compiler:
  - gcc
  - clang

#before_install: ./scripts/travis-before-install.sh


before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - cmake --build . --config Release
  - ctest
