# AppVeyor CI build configuration for c-mrcz

# Before cloning the repo, configure git to handle line endings correctly.
init:
  - git config --global core.autocrlf input

# This is the build version displayed on AppVeyor's UI.
# It's incrementally automatically like travis-ci but allows custom formatting.
version: '{build}'

environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_env.cmd"

  matrix:
    - GENERATOR: "Visual Studio 14 2015 Win64"
      CONFIG: Release

build_script:
  - cmd: set PATH=C:\Program Files (x86)\CMake\bin;%PATH%
  - cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\vsvars32.bat"
  - cmd: cmake --version
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake .. "-G%GENERATOR%"
  - cmd: cmake --build . --config "%CONFIG%"

#test_script:
#  - ps: cd _builds
#  - ctest -VV -C "%CONFIG%"
